CREATE TABLE dept(
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  dept_name VARCHAR(225) NOT NULL
);

CREATE TABLE users (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  fname VARCHAR(30),
  lname VARCHAR(30),
  age INTEGER,
  email VARCHAR(100) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(20) NOT NULL,
  college_id VARCHAR(20) UNIQUE,
  usn VARCHAR(20) UNIQUE,
  dept_id INTEGER REFERENCES dept(id),
  batch INTEGER,
  designation VARCHAR(100),
  bio TEXT,
  phone VARCHAR(15),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE courses(
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  instructor_id INTEGER REFERENCES users(id),
  dept_id INTEGER REFERENCES dept(id),
  course_name VARCHAR(255) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE settings(
  id INTEGER PRIMARY KEY REFERENCES users(id),
  theme VARCHAR(20) NOT NULL DEFAULT 'light',
  notifications BOOLEAN NOT NULL DEFAULT TRUE,
  lang VARCHAR(255) NOT NULL DEFAULT 'English',
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE profile(
  id INTEGER PRIMARY KEY REFERENCES users(id),
  bio VARCHAR(255),
  avatar_url VARCHAR(225),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE assignments (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  course_id INTEGER NOT NULL REFERENCES courses(id),
  title VARCHAR(200) NOT NULL,
  descriptions TEXT,
  due_date TIMESTAMPTZ,
  max_marks INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE submissions (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  assignment_id INTEGER NOT NULL REFERENCES assignments(id),
  student_id INTEGER NOT NULL REFERENCES users(id),
  file_url VARCHAR(255),
  submitted_at TIMESTAMPTZ,
  grade DECIMAL(5,2),
  feedback TEXT
);

CREATE TABLE modules (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  course_id INTEGER NOT NULL REFERENCES courses(id),
  module_name VARCHAR(150) NOT NULL,
  descriptions TEXT,
  order_index INTEGER NOT NULL, 
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE content (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  module_id INTEGER NOT NULL REFERENCES modules(id),
  title VARCHAR(200) NOT NULL,
  content_type VARCHAR(30) NOT NULL,
  content_url VARCHAR(300),
  order_index INTEGER NOT NULL
);